In [1]:
import pandas as pd
import csv

In [98]:
words = pd.read_csv('/wordslist.csv')

In [167]:
letters = pd.read_csv('/letters.csv')

In [100]:
c = a.copy()

       words  1  2  3  4  5
0      aaron  a  a  r  o  n
1      abbém  a  b  b  é  m
2      abbéů  a  b  b  é  ů
3      abbéy  a  b  b  é  y
4      abeba  a  b  e  b  a
...      ... .. .. .. .. ..
21918  žďáru  ž  ď  á  r  u
21919  žďáry  ž  ď  á  r  y
21920  žňová  ž  ň  o  v  á
21921  žňové  ž  ň  o  v  é
21922  žňový  ž  ň  o  v  ý

[21923 rows x 6 columns]

In [101]:
def find_letter(df, letter):
    df[letter] = df['words'].str.find(letter, 0)

In [102]:
def replace_letter(df, letter):
    df[letter] = df[letter].replace([0,1,2,3,4], 1)
    df[letter] = df[letter].replace(-1, 0)

## Odtud pouštět další kola

In [150]:
for letter in b.letters:
    find_letter(c, letter)

In [151]:
for letter in b.letters:
    replace_letter(c, letter)

In [168]:
d = c.drop(columns=['words', '1','2','3','4','5']).sum()
f = d.to_frame().reset_index().rename(columns={0: 'score'})

In [153]:
def replace_letter_score(df, letter, score):
    df[letter] = df[letter].replace(1, score)

In [154]:
for index, row in f.iterrows():
    replace_letter_score(c, row['index'], row['score'])

In [156]:
def sum_frame_by_column(frame, new_col_name, list_of_cols_to_sum):
    frame[new_col_name] = frame[list_of_cols_to_sum].astype(float).sum(axis=1)
    return(frame)

In [157]:
sum_frame_by_column(c, 'score', b.letters)
c = c.sort_values(by=['score'], ascending=False)

,words,1,2,3,4,5,a,á,b,c,...,u,ů,v,w,x,y,ý,z,ž,score
412,břiše,b,ř,i,š,e,0,0,18,0,...,0,0,0,0,0,0,0,0,0,282.0
694,dácie,d,á,c,i,e,0,25,0,64,...,0,0,0,0,0,0,0,0,0,338.0
784,děvče,d,ě,v,č,e,0,0,0,0,...,0,0,52,0,0,0,0,0,0,298.0
821,divže,d,i,v,ž,e,0,0,0,0,...,0,0,52,0,0,0,0,0,18,319.0
967,dubče,d,u,b,č,e,0,0,18,0,...,34,0,0,0,0,0,0,0,0,284.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21638,šňůře,š,ň,ů,ř,e,0,0,0,0,...,0,5,0,0,0,0,0,0,0,233.0
21643,šťáře,š,ť,á,ř,e,0,25,0,0,...,0,0,0,0,0,0,0,0,0,253.0
21759,žháře,ž,h,á,ř,e,0,25,0,0,...,0,0,0,0,0,0,0,0,18,253.0
21788,živce,ž,i,v,c,e,0,0,0,64,...,0,0,52,0,0,0,0,0,18,330.0
21872,žábře,ž,á,b,ř,e,0,25,18,0,...,0,0,0,0,0,0,0,0,18,259.0

## Filtrování

**Písmeno X je na Y pozici**

In [159]:
c = c[c['y'] == 'x']

**Písmeno X se nevyskytuje**

In [161]:
c = c[c['x'] == 0]

**Písmeno X někde je**

In [162]:
c = c[c['x'] != 0]

**Písmeno X není Y pozici**

In [163]:
c = c[c['y'] != 'x']

In [166]:
c.sort_values(by=['score'], ascending=False)

,words,1,2,3,4,5,a,á,b,c,...,u,ů,v,w,x,y,ý,z,ž,score
5043,udice,u,d,i,c,e,0,0,0,64,...,34,0,0,0,0,0,0,0,0,347.0
21171,řídce,ř,í,d,c,e,0,0,0,64,...,0,0,0,0,0,0,0,0,0,339.0
5758,zdice,z,d,i,c,e,0,0,0,64,...,0,0,0,0,0,0,0,23,0,336.0
19937,zdice,z,d,i,c,e,0,0,0,64,...,0,0,0,0,0,0,0,23,0,336.0
6842,budce,b,u,d,c,e,0,0,18,64,...,34,0,0,0,0,0,0,0,0,329.0
19970,zdíce,z,d,í,c,e,0,0,0,64,...,0,0,0,0,0,0,0,23,0,324.0
20445,zídce,z,í,d,c,e,0,0,0,64,...,0,0,0,0,0,0,0,23,0,324.0
1035,edice,e,d,i,c,e,0,0,0,64,...,0,0,0,0,0,0,0,0,0,313.0